name: Main Taski Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Print project tree
        run: tree .